import java.util.*;
public class main 
{
	public static int sum[] = new int[5];
	public static void main(String[] args) 
	{
	int [][] sub = new int[5][10];
	Scanner s = new Scanner(System.in);
	System.out.println("Enter the marks for class 6th");
	System.out.println("Enter marks of English");
	sub[0][0]=s.nextInt();
	System.out.println("Enter marks of Hindi");
	sub[0][1]=s.nextInt();
	System.out.println("Enter marks of Maths");
	sub[0][2]=s.nextInt();
	System.out.println("Enter marks of Science");
	sub[0][3]=s.nextInt();
	System.out.println("Enter marks of Computers");
	sub[0][4]=s.nextInt();
	System.out.println("Enter marks of SocialScience");
	sub[0][5]=s.nextInt();
	System.out.println("Enter marks of Sports");
	sub[0][6]=s.nextInt();
	System.out.println("Enter marks of GeneralKnowledge");
	sub[0][7]=s.nextInt();
	System.out.println("Enter marks of Aptitude");
	sub[0][8]=s.nextInt();
	System.out.println("Enter marks of PersonalityTest");
	sub[0][9]=s.nextInt();
	sum[0]=sub[0][0]+sub[0][1]+sub[0][2]+sub[0][3]+sub[0][4]+sub[0][5]+sub[0][6]+sub[0][7]+sub[0][8]+sub[0][9];
	System.out.println("Your total in class 6th is "+sum[0]);
	System.out.println("Your total of Maths and Science in class 6th is " + (sub[0][2]+sub[0][3]));
	
	System.out.println("Enter the marks for class 7th");
	System.out.println("Enter marks of English");
	sub[1][0]=s.nextInt();
	System.out.println("Enter marks of Hindi");
	sub[1][1]=s.nextInt();
	System.out.println("Enter marks of Maths");
	sub[1][2]=s.nextInt();
	System.out.println("Enter marks of Science");
	sub[1][3]=s.nextInt();
	System.out.println("Enter marks of Computers");
	sub[1][4]=s.nextInt();
	System.out.println("Enter marks of SocialScience");
	sub[1][5]=s.nextInt();
	System.out.println("Enter marks of Sports");
	sub[1][6]=s.nextInt();
	System.out.println("Enter marks of GeneralKnowledge");
	sub[1][7]=s.nextInt();
	System.out.println("Enter marks of Aptitude");
	sub[1][8]=s.nextInt();
	System.out.println("Enter marks of PersonalityTest");
	sub[1][9]=s.nextInt();
	sum[1]=sub[1][0]+sub[1][1]+sub[1][2]+sub[1][3]+sub[1][4]+sub[1][5]+sub[1][6]+sub[1][7]+sub[1][8]+sub[1][9];
	System.out.println("Your total in class 7th is "+sum[1]);
	System.out.println("Your total of Maths and Science in class 7th is " + (sub[1][2]+sub[1][3]));
	
	System.out.println("Enter the marks for class 8th");
	System.out.println("Enter marks of English");
	sub[2][0]=s.nextInt();
	System.out.println("Enter marks of Hindi");
	sub[2][1]=s.nextInt();
	System.out.println("Enter marks of Maths");
	sub[2][2]=s.nextInt();
	System.out.println("Enter marks of Science");
	sub[2][3]=s.nextInt();
	System.out.println("Enter marks of Computers");
	sub[2][4]=s.nextInt();
	System.out.println("Enter marks of SocialScience");
	sub[2][5]=s.nextInt();
	System.out.println("Enter marks of Sports");
	sub[2][6]=s.nextInt();
	System.out.println("Enter marks of GeneralKnowledge");
	sub[2][7]=s.nextInt();
	System.out.println("Enter marks of Aptitude");
	sub[2][8]=s.nextInt();
	System.out.println("Enter marks of PersonalityTest");
	sub[2][9]=s.nextInt();
	sum[2]=sub[2][0]+sub[2][1]+sub[2][2]+sub[2][3]+sub[2][4]+sub[2][5]+sub[2][6]+sub[2][7]+sub[2][8]+sub[2][9];
	System.out.println("Your total in class 8th is "+sum[2]);
	System.out.println("Your total of Maths and Science in class 8th is " + (sub[2][2]+sub[2][3]));
	
	System.out.println("Enter the marks for class 9th");
	System.out.println("Enter marks of English");
	sub[3][0]=s.nextInt();
	System.out.println("Enter marks of Hindi");
	sub[3][1]=s.nextInt();
	System.out.println("Enter marks of Maths");
	sub[3][2]=s.nextInt();
	System.out.println("Enter marks of Science");
	sub[3][3]=s.nextInt();
	System.out.println("Enter marks of Computers");
	sub[3][4]=s.nextInt();
	System.out.println("Enter marks of SocialScience");
	sub[3][5]=s.nextInt();
	System.out.println("Enter marks of Sports");
	sub[3][6]=s.nextInt();
	System.out.println("Enter marks of GeneralKnowledge");
	sub[3][7]=s.nextInt();
	System.out.println("Enter marks of Aptitude");
	sub[3][8]=s.nextInt();
	System.out.println("Enter marks of PersonalityTest");
	sub[3][9]=s.nextInt();
	sum[3]=sub[3][0]+sub[3][1]+sub[3][2]+sub[3][3]+sub[3][4]+sub[3][5]+sub[3][6]+sub[3][7]+sub[3][8]+sub[3][9];
	System.out.println("Your total in class 9th is "+sum[3]);
	System.out.println("Your total of Maths and Science in class 9th is " + (sub[3][2]+sub[3][3]));
	
	
	System.out.println("Enter the marks for class 10th");
	System.out.println("Enter marks of English");
	sub[4][0]=s.nextInt();
	System.out.println("Enter marks of Hindi");
	sub[4][1]=s.nextInt();
	System.out.println("Enter marks of Maths");
	sub[4][2]=s.nextInt();
	System.out.println("Enter marks of Science");
	sub[4][3]=s.nextInt();
	System.out.println("Enter marks of Computers");
	sub[4][4]=s.nextInt();
	System.out.println("Enter marks of SocialScience");
	sub[4][5]=s.nextInt();
	System.out.println("Enter marks of Sports");
	sub[4][6]=s.nextInt();
	System.out.println("Enter marks of GeneralKnowledge");
	sub[4][7]=s.nextInt();
	System.out.println("Enter marks of Aptitude");
	sub[4][8]=s.nextInt();
	System.out.println("Enter marks of PersonalityTest");
	sub[4][9]=s.nextInt();
	sum[4]=sub[4][0]+sub[4][1]+sub[4][2]+sub[4][3]+sub[4][4]+sub[4][5]+sub[4][6]+sub[4][7]+sub[4][8]+sub[4][9];
	System.out.println("Your total in class 10th is "+sum[4]);
	System.out.println("Your total of Maths and Science in class 10th is " + (sub[4][2]+sub[4][3]));
	s.close();
	}
}